kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: <REPLACE-PVC-NAME>
spec:
  accessModes: 
  - <ACCESS-MODE>
  resources:
    requests:
      storage: <STORAGE>
  storageClassName: <STORAGE-CLASS>
