- name: Create service
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: <REPLACE-SERVICE-NAME>
        labels: 
          app: <LABEL-NAME>
      spec:
        selector: {}
        ports: []
